# Created by newuser for 5.7.1

export HISTSIZE=10000000
export SAVEHIST=10000000
setopt hist_ignore_all_dups

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(direnv hook zsh)"

export NIXPKGS_ALLOW_INSECURE=1

export GOPATH="/home/g/go:/home/g/Projects"
export PATH=$PATH:/home/g/go/bin
export CDPATH=/home/g/Projects/src

alias ssh='TERM=xterm ssh'

alias gmt='go mod tidy'

export GITLAB_URL=""
export GITLAB_TOKEN=""

dbg() {
    cmd=$1
    shift
    echo CGO_ENABLED=0 dlv debug $cmd -- $@
    CGO_ENABLED=0 dlv debug $cmd -- $@
}

function jjq {
    jq -R -r "${1:-.} as \$line | try fromjson catch \$line"
}

alias nvim=nvim
alias vim=nvim


compdef _watson watson

watsonpropmt() {
    RPROMPT="$(watson status)"
}

if [ ! -z "$SCRATCHTERM" ]; then
    precmd() {
        watsonpropmt;
    }
fi
