repositories:
 - name: kyverno
   url: https://kyverno.github.io/kyverno/
 - name: cert-manager
   url: https://charts.jetstack.io
 - name: longhorn
   url: https://charts.longhorn.io
 - name: metallb
   url: https://metallb.github.io/metallb

releases:
- name: kyverno
  namespace: kyverno-system
  chart: kyverno/kyverno

- name: cert-manager
  namespace: cert-manager
  chart: cert-manager/cert-manager
  values:
    - crds:
        enabled: true
        keep: true

- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  postRenderer: ./kustomize.sh
  postRendererArgs: ["./patches/longhorn"]
  values:
    - defaultSettings:
        allowCollectingLonghornUsageMetrics: false
        defaultReplicaCount: 1
    - persistence:
        defaultClassReplicaCount: 1
    - service:
        ui:
          type: "LoadBalancer"
          annotations:
            metallb.io/address-pool: admin-pool

- name: metallb
  namespace: metallb-system
  chart: metallb/metallb
