CONVERT_TO = sparkfun_pm2040

COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes
OS_DETECTION_ENABLE = yes

CAPS_WORD_ENABLE = yes

WPM_ENABLE = yes
RAW_ENABLE = yes

# No LEDs on this board
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no

SRC += bongocat.c
