CONVERT_TO = sparkfun_pm2040

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes

COMMAND_ENABLE = no
CAPS_WORD_ENABLE = yes

WPM_ENABLE = yes
RAW_ENABLE = yes

SRC += bongocat.c
