apiVersion: v1
kind: Service
metadata:
  name: any
  annotations:
    metallb.io/loadBalancerIPs: 192.168.2.130
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    $patch: delete
  - targetPort: 8080
    port: 80
    protocol: TCP
